# Sequence 2 : base du language

Assignment la valeur 1 a la variable a
Cette variable est typé ici c'est un entier = integer = int

In [1]:
a = 1
print(a)
print(type(a))

1
<class 'int'>


Il y adifférent type en python

In [2]:
b = 2.456
print(b)
print(type(b))

2.456
<class 'float'>


On peut effectué des opérations sur ces variable
Notez le changement de type

In [3]:
c = a+b
print(c)
print(type(c))


3.456
<class 'float'>


Gestion des chaine de carractère

In [4]:
s = 'hello'
print(s)
print(type(s))


hello
<class 'str'>


In [5]:
s2 =   "hel'lo"  

In [6]:
s3 = """youpi

éè $ ê


sdfsdfsdf
"""
print(s3)


youpi

éè $ ê


sdfsdfsdf



Opération sur µ

In [7]:
s4 = s3+s2+s3
print(s4)


youpi

éè $ ê


sdfsdfsdf
hel'loyoupi

éè $ ê


sdfsdfsdf



Chaque variable est un objectq ui a des méthodes:

In [8]:
s4.upper()

"YOUPI\n\nÉÈ $ Ê\n\n\nSDFSDFSDF\nHEL'LOYOUPI\n\nÉÈ $ Ê\n\n\nSDFSDFSDF\n"

Formatage des str

In [9]:
s5 = 'ma variable est '+str(c)+' !'
s5


'ma variable est 3.456 !'

In [10]:
s6 = '3.56'
print(s6, type(s6))
f6 = float(s6)
print(f6, type(f6))

3.56 <class 'str'>
3.56 <class 'float'>


In [11]:
s5 = 'ma variable est %f !'%c
s5

'ma variable est 3.456000 !'

In [12]:
s5 = 'mes variables sont %s  %s!'%(f6, 123)
s5

'mes variables sont 3.56  123!'

In [13]:
s5 = 'ma variable est {}'.format(c)
s5

'ma variable est 3.456'

Autre type util : bool et complex

In [14]:
flag1 = True
flag2 = False
flag3 = flag1 and flag2
print(flag1, type(flag1))


True <class 'bool'>


In [15]:
c = 50 + 50j
print(c, type(c))

(50+50j) <class 'complex'>


# Création d'un function

On peut créer des functions avec des variables entrés et une variable de sortie.

Attention a l'indentation celà definit le **block**.

en python c'est 4 espaces.



In [16]:
def mon_add(a, b):
    c = a+b
    s = 'resultat: {}+{}={}'.format(a, b, c)
    return s

res = mon_add(5, 4)
print(res)


resultat: 5+4=9


In [17]:
aa = 3
bb = 77
res = mon_add(aa, bb)
print(res)


resultat: 3+77=80


Il peut y avoir plusieurs varibales de sortie.

In [18]:
def mon_add_bis(a, b):
    c = a+b
    s = 'resultat: {}+{}={}'.format(a, b, c)
    return s, c

res, res2 = mon_add_bis(5, 4)
print(res)
print(res2)


resultat: 5+4=9
9


Python permet d'avoir des variables facultatives.

In [19]:
def mon_add_ter(a, b, c = 1, d = 3):
    t = a+b+c+d
    s = 'resultat: {}+{}+{}+{}={}'.format(a, b, c,d, t)
    return s

res = mon_add_ter(aa, bb)
print(res)
res = mon_add_ter(aa, bb, c = 6, d = 9)
print(res)
res = mon_add_ter(aa, bb, d = 9)
print(res)


resultat: 3+77+1+3=84
resultat: 3+77+6+9=95
resultat: 3+77+1+9=90


Voir uniquement des varibales facultative.

In [20]:
def mon_add_4(c = 1, d = 3):
    t = c+d
    s = 'resultat: {}+{}={}'.format( c,d, t)
    return s

res = mon_add_4() # ici y'a rien
print(res)


resultat: 1+3=4


# Quelques opérateurs courants:
 * addition soustraction
 * multiplication division divisio entiere
 * puissance
 * opérateur boolean
 
Attention en python 2.X et 3.X la divisino n'est pas la même!!!!!! c'est mieux en python3.X

In [21]:
a, b, c = 2, 10, 20
r = a+b*c
print(r)


202


In [22]:
a, b = 3, 10
r = b/a
print(r)
r = b//a # division entire
print(r)


3.3333333333333335
3


In [23]:
a = 27.
r = a**2
print(r)
r = a**(1/3)
print(r)



729.0
3.0


# attention opérateur booléan amélioré
and or not

In [24]:

a = True
b = True
res = not(a or b)
print(res)

False


# attention opérateur booléan classique = agit bit a bit
& | ~

In [25]:
# attention opérateur booléan classique = agit bit a bit
a = 0xFF03
b = 0xF003
res = (a&b)
print(hex(res))

0xf003


# Block conditionnel

In [26]:
pval = .0065424
seuil = 0.001

if pval<seuil:
    print('je suis hyper content')
elif pval==seuil:
    print("personne n'en saura rien")
else:
    print("qui m'a piquer mon cyanure")





qui m'a piquer mon cyanure


# object list

suite d'élément hétrogène.

accessible par index entier.

In [27]:
l = [12, 34., 4, 'lkjlkj' ]
print(l)
print(type(l))


[12, 34.0, 4, 'lkjlkj']
<class 'list'>


In [28]:
l2 = [12, 34.,]  
l3 = l+l2
print(l3)


[12, 34.0, 4, 'lkjlkj', 12, 34.0]


On peut accédé et écrire dans une liste avec son index (zero based)

In [29]:
a = l[1]
a = l[3]
print(l)
l[2] = 40
print(l)


[12, 34.0, 4, 'lkjlkj']
[12, 34.0, 40, 'lkjlkj']


Différent syntax

In [30]:
l = list()
l = []


Ajjout d'un élément  à une liste

In [31]:
l = []
l.append(10.)
l.append('yep')
print(l)

[10.0, 'yep']


In [32]:
l3 = l+l+l+l
l3 = l*4
print(l3)


[10.0, 'yep', 10.0, 'yep', 10.0, 'yep', 10.0, 'yep']


# object dict
collections d'élément hétérogène accesible par clef.





In [33]:
d = dict()
d = { }
d = {'a' : 1., 
     'b' : 60, 
     'c' : 'lkjlkj'  }


In [34]:
print(d['a'])
print(d['c'])


1.0
lkjlkj


In [35]:
d['c'] = 50
print(d['c'])

50


 on peut ajouter un nouvelle pari clef valeur

In [36]:
d['x'] = 'youpi'

In [37]:
print(d.keys())

dict_keys(['x', 'a', 'b', 'c'])


In [38]:
print(d.values())

dict_values(['youpi', 1.0, 60, 50])


# création et importation d'un bibliothèque externe

On peut créer des bibliothèque =module = package de function.
On les utilise avec import




# Exercice 1.1

créer deux fichier:
  * monscript1.py
  * mabibliotheque.py

créer une fonction dans bibliotheque.py

et appeler cette fonction depsui monscript1.py




# Solution 1.1

In [39]:
import bibliotheque

res = bibliotheque.func1(1,2)




ImportError: No module named 'bibliotheque'

# 4 méthodes pour import

In [40]:
# cas 1
import numpy
numpy.zeros(5)


array([ 0.,  0.,  0.,  0.,  0.])

In [41]:
# cas 2
import numpy as np
np.zeros(5)


array([ 0.,  0.,  0.,  0.,  0.])

In [42]:
# cas 3
from numpy import zeros, ones
zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [43]:
# cas 4
from numpy import *
zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

On peut utiliser un sous module

In [44]:
import scipy.signal
scipy.signal.filtfilt

<function scipy.signal.signaltools.filtfilt>