# Sequence 5 : numpy fancy indexing

Numpy permet de manipuler des sous ensemble d'un tableau en lecture/écriture.

Il y a 4 grandes methodes:
  * scalaire
  * par *'slice'*
  * par condition booléene
  * par list d'index



In [3]:
import numpy as np

# reshape

In [4]:
a = np.arange(24)
print(a)
a2 = a.reshape(6,4)
print(a2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [5]:
a3 = a.reshape(4,2,3)
print(a3.shape)
print(a3)

(4, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


Avec dimension jocker= -1

In [6]:
a3 = a.reshape(4,-1,3)
print(a3.shape)

(4, 2, 3)


# Lecture/écriture d'un seul élément

In [7]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
# zeros based
# ligne colonne
e = a[1,1]
e

4

In [9]:
a[1,2] = 1000
a

array([[   0,    1,    2],
       [   3,    4, 1000],
       [   6,    7,    8],
       [   9,   10,   11]])

# Par slice

![title](img/slice.jpeg)

In [10]:
# ne pas comprendre ça (même David)
a = np.arange(6).reshape(1,6) + 10*np.arange(6).reshape(6, 1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [11]:
a2 = a[3:, 0:5:2]
a2

array([[30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

# Par mask boolean

In [12]:
a = np.random.randn(15)
a

array([-0.33443936, -1.87063357,  0.8792382 ,  1.70099656, -0.73770565,
        0.68614495,  0.44529155,  0.79668708,  0.69204342,  1.18456356,
        1.20070403,  0.32648299,  1.81224469,  0.99867659,  0.45225051])

On peut créer un vecteur de booléen facile, et l'utiliser ensuite pour selectioner un sous ensemble.

In [13]:
keep = (a>0.)
keep
print(keep)
not_keep = ~keep # not en boolean
print(not_keep)


[False False  True  True False  True  True  True  True  True  True  True
  True  True  True]
[ True  True False False  True False False False False False False False
 False False False]


In [14]:
a3 = a[keep]
a3

array([ 0.8792382 ,  1.70099656,  0.68614495,  0.44529155,  0.79668708,
        0.69204342,  1.18456356,  1.20070403,  0.32648299,  1.81224469,
        0.99867659,  0.45225051])

# Selection explicite d'une liste

In [15]:
a = np.arange(7)*10
a

array([ 0, 10, 20, 30, 40, 50, 60])

In [16]:
l = [2, 4, 0]
a2 = a[l]
a2

array([20, 40,  0])

# Attention une slice pointe sur le même tableau!!

Un tableau issue d'un même tableau est une *'view'*.



In [17]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a2 = a[2:-2]
a2[:] = a2[:]*-10
a2

array([-20, -30, -40, -50, -60, -70])

In [19]:
a


array([  0,   1, -20, -30, -40, -50, -60, -70,   8,   9])


Sinon il faut faire une copie explicite.

In [20]:
a = np.arange(10)
a3 = a[2:-2].copy()
a3[:] = a3[:]*-10
print(a3)
print(a)

[-20 -30 -40 -50 -60 -70]
[0 1 2 3 4 5 6 7 8 9]


# Exercice 5.1

Voici deux vecteurs:
 * a = np.array([10, 20, 30, 40])
 * b = np.array([-.1, -.2, -.3, -.4])

Il faut obtenir avec le jeu des slices l vecteur suivant:
 * c = np.array([10, -.4, 20, -.3, 30, -.2])



In [21]:
a = np.array([10, 20, 30, 40])
b = np.array([-.1, -.2, -.3, -.4])
c = np.array([10, -.4, 20, -.3, 30, -.2])
print(a)
print(b)
print(c)

[10 20 30 40]
[-0.1 -0.2 -0.3 -0.4]
[ 10.   -0.4  20.   -0.3  30.   -0.2]


# Solution 5.1

# Exercie 5.2
Voici un vecteur
a = np.random.randn(5000)
créer un vecteur b qui enlève les déviants.

M + 2.5*std
M - 2.5*std





# Solution 5.2

# nan = not a number

In [22]:
a = np.arange(5, dtype='float64')
a[2] = np.nan
a

array([  0.,   1.,  nan,   3.,   4.])

In [23]:
b = np.exp(1e40)
b

C:\Users\Dell Xps Sam\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':


inf

# test : np.isinf et np.isnan




In [24]:
np.isinf(b)

True

In [25]:
np.isnan(a)

array([False, False,  True, False, False], dtype=bool)